repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        name: Check - YAML
      - id: end-of-file-fixer
        name: Check - End Files on New Line
      - id: trailing-whitespace
        name: Remove Trailing Whitespace
        stages: [commit, push, manual]
  # - repo: local
  #   hooks:
  #     - id: black
  #       name: Formatting - Black
  #       entry: poetry run black
  #       language: system
  #       types: [python]
  #       require_serial: false
  #     - id: isort
  #       name: Formatting - isort
  #       entry: poetry run isort
  #       language: system
  #       types: [python]
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        name: Formatting - black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Formatting - isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        name: Static Type Checking - mypy
        additional_dependencies: [types-PyYAML]
        exclude: ^tests/
        args:
          [--ignore-missing-imports, --follow-imports=skip, --show-error-codes]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.2.2
    hooks:
      - id: poetry-check
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.2
    hooks:
      - id: prettier
