repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        name: Check - YAML
      - id: end-of-file-fixer
        name: Check - End Files on New Line
      - id: trailing-whitespace
        name: Remove Trailing Whitespace
        stages: [commit, push, manual]
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        name: Formatting - black
        stages: [commit, push, manual]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Formatting - isort
        stages: [commit, push, manual]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        name: Static Type Checking - mypy
        additional_dependencies: [types-PyYAML]
        stages: [commit, push, manual]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.2.2
    hooks:
      - id: poetry-check
        name: Check - Poetry Configuration
        stages: [commit, push, manual]
