repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Formatting - isort
        args:
          [
            "--profile",
            "black",
            "-l",
            "100",
            "multi_line_output",
            "3",
            "src/tmi",
          ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        name: Check - YAML
      - id: end-of-file-fixer
        name: Check - End Files on New Line
      - id: trailing-whitespace
        name: Remove Trailing Whitespace
        stages: [commit, push, manual]
  - repo: local
    hooks:
      - id: black
        name: Formatting - Black
        entry: poetry run black
        language: system
        types: [python]
        require_serial: false
  - repo: local
    hooks:
      - id: mypy
        name: mypy - Static Type Checking
        entry: poetry run mypy
        language: system
        types: [python]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.2
    hooks:
      - id: prettier
