language: python
python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10

# Ubuntu 20.04 (Focal) LTS
os: linux
dist: focal

git:
  depth: false

stages:
  - lint
  - test

# Set the caches
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

# Environment variables
env:
  # Set Matplotlib backend to Agg (Non-interactive, only writes to files)
  - MPLBACKEND=Agg
  - PARALLELIZE=true

# Installs poetry and pre-commit
before_install:
  - curl -sSL https://install.python-poetry.org | python3 -
  - poetry --version
  - pip install coveralls
  - pip install pre-commit

# Installs all packages needed for tmi in a virtual environment
install:
  - poetry install
  - pre-commit install-hooks

jobs:
  include:
    - stage: lint
      script:
        pre-commit run --all-files
    - stage: test
        pytest -randomly-seed=42 -randomly-dont-reorganize -cov=tmi src/tmi

after_success:
  - coveralls

notifications:
  email: false