language: python
python:
  - "3.9"
  # - "3.10" uncomment when python 3.10 is available on travis-ci

os: linux
dist: xenial

git:
  depth: false

stages:
  - Quality
  - Test
  - Pre-Commit
  # - Build
  # - Publish

# Set the caches
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

# Environment variables
env:
  # Set Matplotlib backend to Agg (Non-interactive, only writes to files)
  - MPLBACKEND=Agg


# Installs poetry, nox, and nox-poetry
before_install:
  - curl -sSL https://install.python-poetry.org | python3 -
  - poetry --version
  - pip install nox nox-poetry coveralls

# Installs all packages needed for tmi in a virtual environment
install:
  - poetry install

jobs:
  include:
    - stage: "Quality - 3.9"
      name: "Linting, Type Checking, Safety"
      python: 3.9
      script: nox --force-python 3.9 -s mypy typeguard safety

    - stage: "Test - 3.9"
      name: "Unit Tests"
      python: 3.9
      script: nox --force-python 3.9 -s tests

    - stage: "Pre-Commit - 3.9"
      name: "Git Pre-Commit hooks"
      python: 3.9
      script: nox --force-python 3.9 -s pre-commit

after_success:
  - coveralls

notifications:
  email: false