language: python
python:
  - 3.8
git:
  depth: false

# Ubuntu 22.04 (Jammy) LTS
os: linux
dist: jammy

# Set the cache
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"
    - "$HOME/.cache/pypoetry"

# Environment variables
env:
  global:
    # Set Matplotlib backend to Agg (Non-interactive, only writes to files)
    - MPLBACKEND=Agg

# Installs poetry, pre-commit, coveralls, and upgrades pip
before_install:
  - curl -sSL https://install.python-poetry.org | python3 -
  - poetry --version
  - pip install -U pre-commit coveralls pip

jobs:
  include:
    # We can change the python build version here to whatever we decide on.
    - stage: "Linting, Typechecking, Formatting"
      name: "Linting, Typechecking, Formatting"
      install:
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files
    - stage: "Tests"
      name: "Test"
      install:
        - poetry install --with test
      script:
        - poetry run pytest
    - stage: "Build"
      name: "Build"
      install:
        - poetry install
      script: poetry build

after_success:
  - coveralls

notifications:
  email: false
