language: python
python:
  - "3.9"
  - "3.10"
dist: xenial

git:
  depth: false

stages:
  - Quality
  - Test
  - Pre-Commit
  # - Publish

# Set the caches
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

# Environment variables
env:
  # Set Matplotlib backend to Agg (Non-interactive, only writes to files)
  - MPLBACKEND=Agg

# Installs poetry, nox, and nox-poetry
before_install:
  - curl -sSL https://install.python-poetry.org | python3 -
  - poetry --version
  - pip install nox nox-poetry

# Installs all packages needed for tmi in a virtual environment
install:
  - poetry install

jobs:
  include:
    - stage: Quality
    - name: lint
      script: nox -R -rs mypy
    - name: type
      script: nox -R -rs typeguard
    - name: safety
      script: nox -R -rs safety
    - stage: Test
    - name: test
      script: nox -R -rs tests
    - stage: Pre-Commit
    - name: pre-commit
      script: nox -R -rs pre-commit

after_success:
  - poetry run coveralls
