language: python
python:
  - 3.8
git:
  depth: false

# Ubuntu 20.04 (Focal) LTS
os: linux
dist: focal

# Set the cache
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"
    - "$HOME/.cache/pypoetry"

# Environment variables
env:
  global:
    # Set Matplotlib backend to Agg (Non-interactive, only writes to files)
    - MPLBACKEND=Agg

# Installs poetry, pre-commit, coveralls
before_install:
  - curl -sSL https://install.python-poetry.org | python3 -
  - poetry --version
  - pip install pre-commit
  - pip install coveralls

# Installs all packages needed for tmi in a virtual environment.
# Installs the hooks for checking formatting.
install:
  - poetry install --with dev,test
  - pre-commit install-hooks

# # Run the linting (before_script)
# before_script: pre-commit run --all-files

jobs:
  include:
    # We can change the python build version here to whatever we decide on.
    - stage: "Linting, Typechecking, Formatting"
      name: "Linting, Typechecking, Formatting"
      script: pre-commit run --all-files
    - stage: "Tests"
      name: "Test"
      script: poetry run pytest
    - stage: "Build"
      name: "Build"
      script: poetry build

after_success:
  - coveralls

notifications:
  email: false
