name: Build, Lint and Test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    types: [labeled, opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)


jobs:
  build_lint_test:
    name: Build, Lint and Test
    uses: ./.github/workflows/test.yml
    secrets: inherit


  coverage_upload:
    name: Upload to Coveralls
    needs: [build_lint_test]
    uses: coverallsapp/github-action@master
    with:
      path-to-lcov: coverage.lcov
      github-token: ${{ secrets.GITHUB_TOKEN }}
