name: Build, Lint and Test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    types: [labeled, opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)


jobs:
  build_lint_test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
